Momento/ControlGrpcManager.cs, Momento/DataGrpcManager.cs, Momento/HeaderInterceptor.cs, MomentoIntegrationTest/CacheTest.cs
This is a follow-up pr for the implementation option 2 mentioned [here](https://github.com/momentohq/client-sdk-csharp/pull/37#discussion_r840714313).
=> chore: Make header names that always need to be sent constants

Momento/MomentoSigner.cs, MomentoTest/MomentoSignerTest.cs
Closes https://github.com/momentohq/client-sdk-csharp/issues/43
=> fix: url-encode cache name and key in presigned urls

Momento/MomentoSigner.cs, MomentoTest/MomentoSignerTest.cs
```
➜  client-sdk-csharp git:(rest) ✗ dotnet test --filter FullyQualifiedName~MomentoTest                  
Determining projects to restore...
All projects are up-to-date for restore.
MomentoSdk -> /Users/mjindal/src/client-sdk-csharp/Momento/bin/Debug/netstandard2.1/MomentoSdk.dll
MomentoTest -> /Users/mjindal/src/client-sdk-csharp/MomentoTest/bin/Debug/net6.0/MomentoTest.dll
MomentoIntegrationTest -> /Users/mjindal/src/client-sdk-csharp/MomentoIntegrationTest/bin/Debug/net6.0/MomentoIntegrationTest.dll
Test run for /Users/mjindal/src/client-sdk-csharp/MomentoTest/bin/Debug/net6.0/MomentoTest.dll (.NETCoreApp,Version=v6.0)
Test run for /Users/mjindal/src/client-sdk-csharp/MomentoIntegrationTest/bin/Debug/net6.0/MomentoIntegrationTest.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test …
```
=> feat: Adding a rest keyword to get the rest endpoint

Momento/MomentoSdk.csproj, Momento/Responses/CacheMultiGetFailureResponse.cs, Momento/Responses/CacheMultiGetResponse.cs, Momento/ScsDataClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/CacheTest.cs, MomentoIntegrationTest/SimpleCacheControlPlaneTests.cs
Add `MultiGetAsyc` following the example of `multi_get` in the Python SDK.
Closes #52
=> feat: Add multi get

Momento/Incubating/SimpleCacheClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
This commit changes the `SimpleCacheClient` namespace from `MomentoSdk.Responses` to `MomentoSdk`.
=> fix: Cache client should be in the MomentoSdk namespace.

.gitignore, Momento/ScsDataClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
This PR refactors the code to use optional arguments where appropriate. Many methods were extraneous because of this, so we can now delete a lot of repeated code, eg:
```csharp
public CacheSetResponse Set(string cacheName, string key, string value, uint ttlSeconds) {}
// ...
public CacheSetResponse Set(string cacheName, string key, string value) {}
```
becomes
```csharp
public CacheSetResponse Set(string cacheName, string key, string value, uint? ttlSeconds = null)
```
Where the default for `ttlSeconds` is set in one place.
=> chore: Use optional arguments where appropriate

Momento/Responses/CacheGetResponse.cs, Momento/Responses/CacheMultiGetResponse.cs, Momento/ScsDataClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
Closes #66 
This refactors `MultiGet` to be in line with the latest specifications. Keys can be passed in as either variadic arguments or as an `IEnumerable`; the individual keys can be either  `string` or `byte[]`; and the method can be blocking or async.
To illustrate:
```csharp
var response = client.MultiGet("my-cache", "key1", "key2", "key3");
response.Status(); // [HIT, HIT, MISS]
response.Strings(); // ["value1", "value2", null]
response.ToList(); // list of `CacheGetResponse`, each of which wraps the corresponding key's status and value
```
Similarly:
```csharp
IEnumerable<string> keys;
var response = client.MultiGet("my-cache", keys);
```
=> feat: Refactor multi-get to be in sync with latest spec.

Momento/Incubating/Responses/CacheDictionaryGetAllResponse.cs, Momento/Incubating/Responses/CacheDictionaryMultiSetResponse.cs, Momento/Incubating/Responses/CacheDictonaryMultiGetResponse.cs, Momento/Incubating/SimpleCacheClient.cs
Use concrete types from functions. Initially these were interface
types. While it makes sense to broader function arguments to
interfaces, when the return types are known, we should be explicit
about them.
Additionally there were a couple typos in the argument names.
=> chore: fix return types and typos in dictionary stubs

Momento/Responses/CacheGetResponse.cs, Momento/Responses/CacheMultiSetResponse.cs, Momento/ScsDataClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
Closes #70 
This PR introduces a client-side implementation of multi-set. The user specifies multiple values to set by passing an object that implements the `IDictionary` interface. As usual the user also passes in a TTL:
```csharp
var items = new Dictionary<string, string>() { "key1": "value1", "key2": "value2" };
client.MultiSet(cacheName: "my-cache", items: items, ttlSeconds: 300);
```
Ultimately there are a variety of ways to specify items to set. For example a user may feel more comfortable passing in `IEnumerable<KeyValuePair<string, string>>` as opposed to `IDictionary<string, string>`. We can implement these on demand per feedback.
=> feat: implement multi-set

Momento/Incubating/Responses/CacheDictionaryGetAllResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetMultiResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetResponse.cs, Momento/Incubating/Responses/CacheDictionarySetMultiResponse.cs, Momento/Incubating/Responses/CacheDictionarySetResponse.cs, Momento/MomentoSdk.csproj, Momento/Responses/CacheGetMultiResponse.cs, Momento/Responses/CacheGetResponse.cs, Momento/Responses/CacheInfo.cs, Momento/Responses/ListCachesResponse.cs, Momento/ScsControlClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/MomentoIntegrationTest.csproj, MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs, MomentoTest/MomentoSignerTest.cs, MomentoTest/MomentoTest.csproj
Closes #80 
Enable nullable reference types (NRT) and null static analysis in the
projects. With this setting the compiler issues warnings when
variables/arguments are in the wrong null context. This PR enables the setting,
resolves remaining NRT warnings, and removes previously per-file
nullable-enabled directives.
NRT enabled is best practice in new projects and documented here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings
https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types
https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies
=> chore: enable nullable reference types in projects

MomentoIntegrationTest/Fixtures.cs, MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs, MomentoIntegrationTest/Usings.cs
This PR introduces a client test fixture. The previous tests
instantiated the client in test class constructors. That is, we used
this pattern:
```csharp
public class MyTests
{
public MyTests()
{
// Instantiate the client
}
public void Test_Something()
{
// tests using the client
}
public void Test_Otherthing()
{
// tests using the client
}
}
```
Data instantiated in the constructor will be setup and torn down
for *each* test method, not just for the class as a whole. Because
an isolated client is not necessary for most of the tests and incurs
high overhead, we should avoid this.
In `Fixtures.cs` we create a client fixture and register it to be
available across all test classes. We updated the test cases accordingly.
See [the official documentation](https://xunit.net/docs/shared-context) …
=> chore: use client test fixture to speedup tests

MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs, MomentoIntegrationTest/Utils.cs
This PR replaces ad-hoc test data with GUIDs. The code is easier to
maintain and less error prone (keys leaking from one test to the
other).
We also refactored test functions to a separate `Utils.cs` file.
=> chore: use guids instead of ad-hoc strings in tests

Momento/ControlGrpcManager.cs, Momento/DataGrpcManager.cs, Momento/Responses/CacheGetMultiResponse.cs, Momento/Responses/CacheGetResponse.cs, Momento/Responses/CacheInfo.cs, Momento/Responses/CacheSetMultiResponse.cs, Momento/Responses/ListCachesResponse.cs, Momento/ScsControlClient.cs, Momento/ScsDataClient.cs, MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
Customers and a language expert have recommended to use properties
where appropriate. Since many response objects just wrap data, we
should use properties to access that data.
For reference: [C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties)
=> chore: prefer properties to basic getter accessors

Momento/Responses/CacheGetMultiResponse.cs, Momento/Responses/CacheGetResponse.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
We have decided that the convenience methods will use UTF-8 only. A future PR may enable other encodings depending on customer use cases.
=> chore: removing encoding from get response

Momento/ISimpleCacheClient.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Internal/ScsDataClient.cs, Momento/Internal/Utils.cs, Momento/Responses/CacheSetMultiResponse.cs, Momento/Responses/CacheSetResponse.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
This changes the client API to use the broadest interfaces where possible. `IEnumerable<KeyValuePair>` affords the end-user more options than `IDictionary` without limiting the implementation.
While updating this, we corrected the implementation of `CacheSetMultiResponse` to not propagate user-data. And while doing this made some minor style changes to the data client.
=> chore: prefer ienumerable over dictionary + other style issues

Momento/MomentoSdk.csproj
Pull the gRPC generated messages and client from NuGet.
=> feat: reference protos from NuGet

Momento/ISimpleCacheClient.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Incubating/SimpleCacheClientFactory.cs, Momento/MomentoSdk.csproj, Momento/MomentoSigner.cs, Momento/Requests/SigningRequest.cs, Momento/SimpleCacheClient.cs, MomentoTest/MomentoSignerTest.cs
This enables documentation in the SDK assembly. By default the `dotnet` tooling does not enable this. We have enabled this and also completed documentation for the cache client and signer classes.
In a future PR we will complete documentation for all public classes and methods in the SDK assembly.
=> chore: update documentation

.github/workflows/cd.yaml, .github/workflows/ci.yaml, IncubatingIntegrationTest/Fixtures.cs, IncubatingIntegrationTest/TestBase.cs, MomentoIntegrationTest/Fixtures.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
Closes #104.
This adds the incubating integration tests to the continuous
integration and deployment jobs. Previously we ran these tests offline
due to the prior nature of the backing service.
This also externalizes the test cache name to use the (already
present) environment variable.
=> fix: add incubating integration tests to CI/CD

Momento/MomentoSdk.csproj
In a future PR we will address public-facing documentation. For now we
will suppress the multitudinous warnings by disabling the warning
project wide.
=> chore: temporarily disable CS1591 / missing documentation

Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/Responses/CacheDictionaryFetchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetBatchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetResponse.cs, Momento/Incubating/Responses/CacheSetFetchResponse.cs, Momento/Internal/ControlGrpcManager.cs, Momento/Internal/DataGrpcManager.cs, Momento/Internal/ScsControlClient.cs, Momento/Internal/ScsDataClient.cs, Momento/MomentoSdk.csproj, Momento/Responses/CacheGetResponse.cs, Momento/Responses/CacheGetStatus.cs, Momento/Responses/CacheSetResponse.cs, Momento/Responses/ListCachesResponse.cs, MomentoTest/Responses/CacheGetResponseTest.cs
This updates to the latest protos. These properly namespace the protos
to `Momento.Protos`, hence the updates necessary to the client code
here.
=> chore: update protos dependency

IncubatingIntegrationTest/DictionaryTest.cs, IncubatingIntegrationTest/ListTest.cs, IncubatingIntegrationTest/SetTest.cs, Momento/ISimpleCacheClient.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
This PR removes methods with variadic args. These overloads are
undesirable for a few reasons:
(1) They add considerable surface area to SDK.
(2) Because the arguments (cache keys/values) are variable length,
they go at the end of the method signature. This breaks the pattern
where the cache keys/values go after the cache name.
(3) Mixed support across languages. We want to add the most common
case first. In most languages, the common case is not variable length
arguments as opposed to lists.
=> chore: remove methods with variadic args

IncubatingIntegrationTest/DictionaryTest.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/README.md, Momento/Incubating/Responses/CacheDictionaryFetchResponse.cs, Momento/Incubating/SimpleCacheClient.cs
Add overloads for `DictionarySet` and `DictionarySetBatch` to accept `string` fields and `byte[]` values. Also support marshalling  `DictionaryFetch` results to `Dictionary<string, byte[]>`.
Closes #119
=> chore: add dictionary set and fetch overloads

IncubatingIntegrationTest/SetTest.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/Responses/CacheSetRemoveElement.cs, Momento/Incubating/Responses/CacheSetRemoveElements.cs, Momento/Incubating/SimpleCacheClient.cs
Implement, test, and document the commands `SetRemoveElement` and `SetRemoveElements`.
Closes #118
=> feat: implement `SetRemoveElementAsync` and `SetRemoveElementsAsync`

IncubatingIntegrationTest/ListTest.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Internal/Utils.cs
Add an optional `truncateTailToSize` (`truncateHeadToSize`) to `LishPushFront` (`ListPushBack`). This argument will trigger the list to be trimmed on the opposite end of the push if the size exceeds the specified value. This PR adds the argument to the method signatures as well as checks that it is strictly positive. A future PR will make this functional.
Progress towards #122 .
=> feat: add stub parameter to `ListPush` to truncate after size.

IncubatingIntegrationTest/ListTest.cs, Momento/Incubating/SimpleCacheClient.cs
For `ListPush` We use the nouns "Front" and "Back" to refer to the
beginning and end of the list respectively. In the previous commit, in the
context of truncate, we used the nouns "Head" and "Tail". That introduced 
extra vocabulary to refer to exactly the same concepts. This commit renames
"Head" and "Tail" to "Front" and "Back" for consistency.
=> fix: make truncate*ToSize nomenclature consistent with `ListPush*`

tests/Integration/Momento.Sdk.Incubating.Tests/DictionaryTest.cs, tests/Integration/Momento.Sdk.Incubating.Tests/ListTest.cs, tests/Integration/Momento.Sdk.Incubating.Tests/SetTest.cs
The `RefreshTtl` integration tests rely on delays to exercise the
feature. The TTLs before are too tight for the CI/CD server env, and cause
intermittent failures due to network latencies as opposed to the
feature under test not working. This change relaxes the timings to
account for latencies.
=> fix: relax integration test timings

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, src/Momento.Sdk/Internal/Utils.cs
Use the breadth of .NET documentation tags where appropriate. The previous code had markdown in places which will not display correctly in Intellisense.
This also reduces a lot of copy-paste documentation by using `inheritdoc`.
Closes #127
=> docs: use documentation tags where appropriate

src/Momento.Sdk/Incubating/Internal/ScsDataClient.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Incubating.Tests/ListTest.cs
Renaming for clarity: `ListRemoveValue` removes all instances of `value` from a list.
=> chore: rename `ListRemoveAll` to `ListRemoveValue`

src/Momento.Sdk/Incubating/Internal/ScsDataClient.cs, src/Momento.Sdk/Incubating/Responses/CacheListLengthResponse.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Incubating.Tests/ListTest.cs
Implements, tests, and documents `ListLengthAsync`. A list not in the
cache is interpreted to have length 0.
Closes #133
=> feat: implement `ListLength`

src/Momento.Sdk/Incubating/Responses/CacheDictionaryIncrementResponse.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Incubating.Tests/DictionaryTest.cs
This introduces a stub command and response object for `DictionaryIncrement`. A user interacts with a numeric dictionary value using `DictionaryIncrementAsync`. Additionally a user may reset, set, or get values using the normal `DictionarySet` and `DictionaryGet` commands, operating on string representations of integers.
See the documentation for `DictionaryIncrementAsync` for examples.
Closes #138
=> feat: dictionary increment stub

src/Momento.Sdk/Incubating/Internal/ScsDataClient.cs, src/Momento.Sdk/Incubating/Responses/CacheListPushBackResponse.cs, src/Momento.Sdk/Incubating/Responses/CacheListPushFrontResponse.cs, src/Momento.Sdk/Incubating/Responses/CacheListRemoveValueResponse.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Incubating.Tests/ListTest.cs
This fixes two minor issues:
1. The `ListRemoveValue` response had an out of date name. Changed to `CacheListRemoveValue`
2. Added list length to the response for `ListPushFront` and `ListPushBack` 
Closes #144
=> fix: remove value response name and list push length

.github/workflows/cd.yaml, .github/workflows/manual-release.yaml, .github/workflows/on-push-to-release-branch.yaml
Updates the `cd.yaml` job so that we don't do a release on
every commit.  Introduces a new manual release job that we
can use to decide when to do a release.  Releases will come
from the `release` branch rather than the `main` branch.
=> feat: release from release branch

.github/workflows/ci.yaml, src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs, src/Momento.Sdk/Exceptions/FailedPreconditionException.cs, src/Momento.Sdk/Incubating/Internal/ScsDataClient.cs, src/Momento.Sdk/Incubating/Responses/CacheDictionaryIncrementResponse.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, tests/Integration/Momento.Sdk.Incubating.Tests/DictionaryTest.cs
Implement `DictionaryIncrementAsync` and add integration tests. Handles error case where one tries to increment a field that doesn't store a number.
Closes #152
=> feat: implement dictionary increment

.github/workflows/ci.yaml
The CI job uses a github action that sends e-mails to us on build failures.
That action was defined in the examples repo, and when I moved
the dotnet examples over to this repo I didn't bring that action
along, so there was a bad reference to it in the ci.yaml.
Now that action has been moved to standards-and-practices repo
so it can be shared across other projects.  This commit fixes
the reference to point to the standards-and-practices repo.
=> fix: bad reference to error email action

src/Momento.Sdk/Momento.Sdk.csproj
This fixes the SDK assembly metadata to reference the correct repo and examples location.
=> docs: assembly metadata references new sdk and examples locations

src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs
The failed precondition switch statement was not taking into account the switch statement fall through behavior. In the previous location, we would raise `FailedPrecondition` for `InvalidArgument` or `OutOfRange` gRPC status codes, which is not what we want.
=> fix: move failed precondition to correct location

.github/workflows/on-push-to-release-branch.yaml
This ports the workaround to get semrel working on the release branch, as opposed to the main branch only.
=> fix: use semrel-from-release-branch workaround

src/Momento.Sdk/Momento.Sdk.csproj
Targeting netstandard2.0 opens backwards compatibiltiy to .NET Framework versions 4.6.1+. This supports users with much older codebases without API sacrifice on our part.
Closes #164
=> feat: change target framework to netstandard2.0

examples/MomentoApplication/MomentoApplication.csproj, src/Momento.Sdk/Exceptions/AlreadyExistsException.cs, src/Momento.Sdk/Exceptions/AuthenticationException.cs, src/Momento.Sdk/Exceptions/BadRequestException.cs, src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs, src/Momento.Sdk/Exceptions/CancelledException.cs, src/Momento.Sdk/Exceptions/FailedPreconditionException.cs, src/Momento.Sdk/Exceptions/InternalServerException.cs, src/Momento.Sdk/Exceptions/InvalidArgumentException.cs, src/Momento.Sdk/Exceptions/LimitExceededException.cs, src/Momento.Sdk/Exceptions/NotFoundException.cs, src/Momento.Sdk/Exceptions/PermissionDeniedException.cs, src/Momento.Sdk/Exceptions/SdkException.cs, src/Momento.Sdk/Exceptions/TimeoutException.cs, src/Momento.Sdk/Exceptions/UnknownException.cs
Adds errorCode and transportDetails properties.
=> feat: update SdkException and subtypes

examples/MomentoLoadGen/Program.cs
This makes the following improvements to the load generator:
* Handles throttles without crashing
* Handles timeouts without crashing
* Adds a very simplistic implementation of a "max requests per second" setting,
which can be used to rate-limit the load generator on the client side
=> chore: improvements to load generator

src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/SimpleCacheClient.cs
This PR allows the cache client to accept a `ILoggerFactory` parameter. This is used to create loggers in the cache client itself, any contained objects, and so on.
We allow the `loggerFactory` to be `null`. In this case we use the `NullLoggerFactory` singleton to create concrete loggers. Those loggers will just perform no-ops.
=> feat: add logger to client

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Middleware/IMiddleware.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/PassThroughMiddleware.cs, src/Momento.Sdk/Exceptions/SdkException.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Middleware/FairAsyncSemaphore.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/CreateCacheResponse.cs, src/Momento.Sdk/Responses/DeleteCacheResponse.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs
During tuning, I discovered that the .NET grpc library behaves differently than the others I'd previously tested w/rt connections opened to the server.  Specifically, it will detect whenever your number of concurrent requests exceeds a multiple of 100 and open a new connection to the server when it does.  Thus, in my loadgen scenario where I was executing 5000 concurrent requests, the library would end up opening on the order of 50 connections to the server.
This behavior is undesirable for both the client and server, depending on the network bandwidth available between the two.  Specifically, in a laptop environment, throughput and latency both decrease when you exceed about 200 concurrent requests, so there is no value in opening so many additional connections to the server and this …
=> feat: max concurrent request middleware

src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/SimpleCacheClient.cs
For internal classes we want to make it a required argument, so that we don't ever mistakenly omit it.
=> chore: LoggerFactory should only be nullable for public-facing classes

src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Transport/IGrpcConfiguration.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs
This commit updates our interface for the gRPC settings.
The original version was built based on the specification
doc that I wrote, which was in turn based on tuning work
done with our JavaScript SDK.  In .NET it turns out that
the settings we were configuring for JS aren't relevant,
and furthermore the .NET gRPC library only exposes a much
more strongly-typed interface into what gRPC channel options
you can configure.  This is largely what we were trying
to accomplish with our abstraction, so it makes more sense
for this SDK to just expose the .NET one directly, which
is what we do in this commit.
=> chore: wire up grpc settings from Configuration

src/Momento.Sdk/Internal/DataGrpcManager.cs
As discussed with @cprice404 , @pgautier404 , and @malandis, I added back the advanced data structure signatures  `DataGrpcManager` so that when the incubating uses this SDK, those operations can be called.
We decided to add these back instead of copying/pasting `DataGrpcManager` to the incubating repo since these are internal so they won't be exposed to the users and also we won't need to update `DataGrpcManager` in the incubating repo every time changes occur in the production SDK.
=> chore: add advanced data structure signatures

src/Momento.Sdk/Momento.Sdk.csproj
Modifies the NuGet package to include debug symbols and sources.
Closes #217
=> chore: include debug symbols and sources

src/Momento.Sdk/Config/Configurations.cs
In the dogfood test, these aliases were reported more confusing than helpful. Thus we are removing them.
Closes #219
=> chore: remove pre-built config aliases

src/Momento.Sdk/Momento.Sdk.csproj
The recommended `SymbolPackageFormat` is `snupkg`. The default is
deprecated. See the note here: https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
=> chore: use snupkg format

src/Momento.Sdk/Momento.Sdk.csproj
SourceLink is an official supported mechanism to link source code to a
NuGet package. See: https://github.com/dotnet/sourcelink
=> chore: use sourcelink

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Responses/CacheDeleteResponse.cs, src/Momento.Sdk/Responses/CacheGetResponse.cs, src/Momento.Sdk/Responses/CacheSetResponse.cs, src/Momento.Sdk/Responses/CreateCacheResponse.cs, src/Momento.Sdk/Responses/DeleteCacheResponse.cs, src/Momento.Sdk/Responses/ListCachesResponse.cs, src/Momento.Sdk/docs.xml
Some of these comments may need to be copied into `SimpleCacheClient.cs`, but if that work is determined to be necessary it'll be done in a separate PR.
=> chore: response pattern matching doc comments

tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheDataTest.cs
This PR explicitly tests class type assertions. Previously these were implicit, which makes failures harder to identify in the test runner results.
Closes #266
=> chore: make class casts asserts in tests

src/Momento.Sdk/Momento.Sdk.csproj
This commit attempts to pare down our dependency list to the
minimum requirements to compile.  Previously we had more than
one gRPC library, plus a google protobuf lib that we don't seem
to need.
This also removes the SourceLink.Github because it wasn't required
for compiling, but that is probably a mistake and should be
reverted... just posting this for discussion since I'm not familiar
with that one.
=> fix: remove unnecessary deps (e.g. duplicate grpc dep)

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/IConfiguration.cs, src/Momento.Sdk/Config/Middleware/IMiddleware.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/PassThroughMiddleware.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Retry/IRetryStrategy.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/SimpleCacheClient.cs
This commit does some re-working on how we expose and curry the
logging config (ILoggerFactory).
The motivation for this PR is that many (most?) Middlewares and
Retry Strategies will need access to the logging config, and it
is very cumbersome to try to pass it in as a constructor arg
to every single one of those.  Especially in the pre-built configs,
which currently do not even have direct access to the ILoggerFactory.
To address this we move the ILoggerFactory to be a first-class
member of the IConfiguration itself.  We also alter the constructors
for the Configuration class such that it will loop over all of the
Middlewares and the RetryStrategy and set the ILoggerFactory on them
if they do not already have one.
This ensures that customers only ever need to explictly pass the …
=> fix: re-work logging config

src/Momento.Sdk/Auth/EnvMomentoTokenProvider.cs, src/Momento.Sdk/Auth/ICredentialProvider.cs, src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Momento.Sdk.csproj
This pr address the first 20 warnings of 165 warning we have for documentation.
Relevant ticket: https://github.com/momentohq/client-sdk-dotnet/issues/223
=> fix: re-enable warning and address 20 warnings

src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs
In Middleware code, if you need to modify the response before it
makes it back out to the caller, you need to use `Task.ContinueWith`.
However, if an exception is thrown while such a Middleware is
in the stack, the exception will get wrapped in an AggregateException.
Prior to this commit our CacheExceptionMapper would treat this as
an unknown error and we would lose our desired status code mapping.
This commit unwraps AggregateExceptions before the mapping so that
the error codes will be correct.
It also adds debug logs to the exception mapper so that we can
see what's going wrong if other exception types fail to map
properly in the future.
=> fix: handle AggregateExceptions from task continuations

src/Momento.Sdk/Config/Middleware/IMiddleware.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/PassThroughMiddleware.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Retry/IGrpcRequest.cs, src/Momento.Sdk/Config/Retry/IGrpcResponse.cs, src/Momento.Sdk/Config/Retry/IRetryEligibilityStrategy.cs, src/Momento.Sdk/Config/Retry/IRetryStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Middleware/HeaderMiddleware.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, src/Momento.Sdk/Internal/Middleware/MiddlewareExtensions.cs, src/Momento.Sdk/Internal/Middleware/RetryMiddleware.cs, src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj
This commit adds an initial implementation of a retry middleware, along with fleshing out the FixedCountRetryStrategy for compatibility with the new middleware.  As of this commit, any Get/Set requests that fail with an Unavailable or Internal error gRPC status code will be retried up to 3 attempts.
There is no backoff or jitter yet; we should implement that in the future.
The determination of which gRPC status codes and request types are eligible for retries is implemented via a new IRetryEligibilityStrategy interface.  This way, individual retry strategies have the ability to override the behavior, but in the 90% case they can just re-use the default eligibility strategy.
NOTE: we implement retries as a bespoke middleware rather than using the retry configuration that is built into the …
=> feat: add basic retry middleware

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/IConfiguration.cs, src/Momento.Sdk/Config/Middleware/IMiddleware.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/PassThroughMiddleware.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Retry/IRetryStrategy.cs, src/Momento.Sdk/Internal/Middleware/HeaderMiddleware.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, src/Momento.Sdk/Internal/Middleware/RetryMiddleware.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs
Kenny called out on a previous PR that there was some code smell in the way I was managing the logging factories for the various components of the configuration.
This commit reworks things slightly so that the user still only has to pass in the ILoggerFactory in one spot in our pre-built configs, but we now just pass that directly through to the constructors of the other things that need it.  This allows us to get rid of the getters and copy constructors that we had previously exposed.
=> feat: simplify logging configuration

README.template.md, examples/MomentoApplication/README.md, examples/MomentoLoadGen/README.md, examples/MomentoUsage/README.md
This PR adds READMEs to each of the example application directories and includes small updates to existing docs.
=> chore: readme updates and additions

examples/MomentoLoadGen/Program.cs
This is pr is to add a print statement so that we can export the data to a csv file for easy visualization of load gen data.
Python load gen print statement reference: [link](https://github.com/momentohq/client-sdk-examples/commit/0df323dc770ed1e7b94bf803012db632eacb3fb9#diff-c92ea588ade78f0b0c1a09a4400572066bf51393877e00008803934e73c85eafR266)
Related ticket: https://github.com/momentohq/client-sdk-dotnet/issues/234
=> chore: add print statement for generating csv data

src/Momento.Sdk/Auth/StringMomentoTokenProvider.cs, src/Momento.Sdk/Auth/Utils.cs, src/Momento.Sdk/Config/IConfiguration.cs, tests/Unit/Momento.Sdk.Tests/Auth/StringMomentoTokenProviderTest.cs
Adds a new auth provider to read from a string passed in. This is used in examples when prompting for an auth token at the command line.
=> chore: add string auth provider

src/Momento.Sdk/Responses/CacheDeleteResponse.cs, src/Momento.Sdk/Responses/CacheGetResponse.cs, src/Momento.Sdk/Responses/CacheSetResponse.cs, src/Momento.Sdk/Responses/CreateCacheResponse.cs, src/Momento.Sdk/Responses/DeleteCacheResponse.cs, src/Momento.Sdk/Responses/ListCachesResponse.cs, src/Momento.Sdk/docs.xml, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs
This commit changes the name of the `Exception` object on our
Error classes to `InnerException`.  This seems like the pattern
that is used in the existing C# exception object model for
cases like ours, where you don't usually expect the caller to
dig into the nested error details but you want to make it possible
for them to do so.
=> feat: Rename `Exception` to `InnerException`

src/Momento.Sdk/Config/Configurations.cs
Ran the load gen with the suggested numbers/platforms in the ticket and finalized the inputs.
https://github.com/momentohq/client-sdk-dotnet/issues/234#issuecomment-1275350997
Closes #234
=> chore: update pre-built config numbers for timeout, concurrent requests

src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Middleware/LoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/PassThroughMiddleware.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Retry/IRetryEligibilityStrategy.cs, src/Momento.Sdk/Config/Transport/IGrpcConfiguration.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Exceptions/AlreadyExistsException.cs, src/Momento.Sdk/Exceptions/AuthenticationException.cs, src/Momento.Sdk/Exceptions/BadRequestException.cs, src/Momento.Sdk/Exceptions/CancelledException.cs, src/Momento.Sdk/Exceptions/FailedPreconditionException.cs, src/Momento.Sdk/Exceptions/InternalServerException.cs, src/Momento.Sdk/Exceptions/InvalidArgumentException.cs, src/Momento.Sdk/Exceptions/LimitExceededException.cs, src/Momento.Sdk/Exceptions/NotFoundException.cs, src/Momento.Sdk/Exceptions/PermissionDeniedException.cs, src/Momento.Sdk/Exceptions/SdkException.cs, src/Momento.Sdk/Exceptions/ServerUnavailableException.cs, src/Momento.Sdk/Exceptions/TimeoutException.cs, src/Momento.Sdk/Exceptions/UnknownException.cs, src/Momento.Sdk/Exceptions/UnknownServiceException.cs, src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs, src/Momento.Sdk/docs.xml
This fills in the remaining docstrings to get rid all of the remaining compiler warnings.
=> chore: zero inbox on docstring warnings

README.template.md, docs/advanced-config.md
Tweaks the ordering of the README sections a bit to make the
examples more prominent and highlight the pattern matching
earlier.
Also adds an initial doc for advanced configuration.
The README template generator will need to be tweaked to
accommodate these changes but this feels like a better
structure based on the feedback we got in the bug bash.
=> chore: hopefully final touches to README

tests/Integration/Momento.Sdk.Tests/SimpleCacheDataTest.cs
The new API returns errors instead of throwing exceptions. The tests were written for exceptions, updated to test for errors, but the function names were out of date.
=> chore: rename tests to reflect errors instead of throwing exception

src/Momento.Sdk/Internal/ExtensionMethods/ByteArrayExtensions.cs, src/Momento.Sdk/Internal/ExtensionMethods/DictionaryExtensions.cs, src/Momento.Sdk/Internal/ExtensionMethods/ListExtensions.cs, src/Momento.Sdk/Internal/ExtensionMethods/StringExtensions.cs, src/Momento.Sdk/Internal/ExtensionMethods/ToByteStringExtensions.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/Responses/CacheGetResponse.cs, tests/Unit/Momento.Sdk.Tests/Internal/ExtensionMethods/ByteArrayExtensionsTest.cs, tests/Unit/Momento.Sdk.Tests/Internal/ExtensionMethods/StringExtensionsTest.cs, tests/Unit/Momento.Sdk.Tests/Responses/CacheGetResponseTest.cs
This adds extension methods to both pretty print byte arrays and truncate strings. With these extension methods we trim the string representation of `CacheGetResponse.Hit`.
Closes #314
=> chore: truncate long CacheGetResponse.Hit string representations

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, README.ja.md
Updated the `on-push-to-main` workflow to take `project_stability=stable` and removed the beta warning from JP README.
=> chore: update GH workflow arg and JP `README`

src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs, src/Momento.Sdk/Internal/ScsDataClient.cs
This PR moves attaching the transport metadata to the exception
converter, where the transport details are created. This reduces
duplicated code in the data client.
=> chore: dry exception handling

CONTRIBUTING.md, src/Momento.Sdk/Internal/LoggingUtils.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/Momento.Sdk.Tests.Integration.csproj
This commit adds logging for all requests; it will be visible
if your Microsoft.Extensions.LoggerFactory configuration
logs at TRACE level for the Momento SDK namespaces.
After this goes in I will do a similar thing in the incubating repo.
=> feat: add logging for all requests at TRACE level

src/Momento.Sdk/Internal/DataGrpcManager.cs
With the new version of the service, we will not isolate keys based on
type. Because of this, we do not need a dedicated `delete` RPC for
each type.
addresses https://github.com/momentohq/client-sdk-dotnet-incubating/issues/65
=> feat: remove deprecated call

src/Momento.Sdk/Internal/DataGrpcManager.cs
Previously we removed the `DictionaryDeleteAsync` method believing it
was single use for deleting an entire dictionary. To the contrary, the
RPC is used for deleting field(s) as well, so we must restore it.
=> fix: reverts pr #337 (commit a394a)

src/Momento.Sdk/Momento.Sdk.csproj
Update the SDK to use the latest client protos, which include the `SetIfNotExists` API.
This API will be implemented in the `Incubating` version of the SDK for now, but that pulls in its dependency on the protos via this repo, so the protos must be updated here even if they are not implemented yet.
=> chore: Update protos to 0.38.0

src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs
Adds support to retry idempotent data structure operations. The only
commands at this point that are not idempotent are (i) ones that add or
delete from a list positionally, and (ii) increment.
closes https://github.com/momentohq/client-sdk-dotnet-incubating/issues/55
=> feat: retry data structure commands

src/Momento.Sdk/Auth/EnvMomentoTokenProvider.cs, src/Momento.Sdk/Auth/ICredentialProvider.cs, src/Momento.Sdk/Auth/StringMomentoTokenProvider.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheEagerConnectionTest.cs
This commit adds a configuration setting that can be used to enable eager connection to the server when the client is constructed.  By default, the client establishes the connection lazily when the first request is executed.  However, this approach can lead to request timeouts on the first request if the connection takes too long to establish, because the connection time is counted toward the client-side timeout. When eager connections are enabled, the client will attempt to establish the connection to the server at construction time, which means that the connection will already be established before the first user request is issued.
=> feat: add support for configuring eager connection on client

src/Momento.Sdk/Config/Transport/IGrpcConfiguration.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/SimpleCacheClient.cs
This commit adds a setting to gRPC config that allows users to configure a minimum number of gRPC channels.  Prior to this, the client would always construct a single channel and would dynamically add additional ones only after we exceeded the maximum number of concurrent requests on the current channels. This results in imbalanced load on the server for cases where the number of concurrent requests remains below the threshold.
Users with this type of workload can increase this new setting to ensure they have more than one connection to the servers, and thus increase the likelihood of balancing requests across multiple servers for improved performance.
=> feat: support configuring a minimum number of gRPC channels

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, .github/workflows/on-push-to-release-branch.yaml
To prevent collisions when running multiple actions at the same time,
we append the commit sha to the cache name to make it unique.
Closes #372
=> chore: use unique cache name for CI jobs

src/Momento.Sdk/ISimpleCacheClient.cs
There were two minor typos in the interface which this fixes.
=> fix: argument name typos

Makefile
Similar to the python repo, we add a makefile. This will help a
new (or returning) contributor onboard to the dotnet toolchain
quicker.
=> chore: add project makefile

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/SimpleCacheClient.cs
We rename dictionary "items" (field value pairs) to elements. That way
the way refer to an abstract collections contents (elements) is
consistent across dictionaries, sets, lists, etc. This change is
consistent with other SDKs.
Closes #365
=> chore: rename dictionary items to elements

src/Momento.Sdk/Internal/ExtensionMethods/DictionaryExtensions.cs, src/Momento.Sdk/Internal/ExtensionMethods/ListExtensions.cs, src/Momento.Sdk/Responses/CacheDictionaryFetchResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldsResponse.cs, src/Momento.Sdk/Responses/CacheListFetchResponse.cs, src/Momento.Sdk/Responses/CacheSetFetchResponse.cs
Refactor the response types to return/contain interfaces to
collections instead of concrete collection types. This allows greater
flexiblity for developers to mock and integrate the responses.
Closes #376
=> refactor: use interfaces for collections in response types

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/Middleware/HeaderMiddleware.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, src/Momento.Sdk/Internal/Middleware/RetryMiddleware.cs, src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs
Users may want to avoid the possibility of us making changes to
the tuning settings in our pre-built configs between releases.
This commit renames the current versions to v1(), and converts
the latest() factory fns into aliases to v1(). This way
in the future we can introduce v2's if necessary without worrying
about rolling out unexpected/undesired config changes to users
who have pinned to v1.
Closes #368
=> feat: add v1 pre-built configurations

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Responses/ListCachesResponse.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs
Pending server side support, we remove the next token param from the
list caches control operation.
Closes #382
=> feat: remove next token param from list caches

src/Momento.Sdk/Responses/CacheDictionaryGetFieldResponse.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/DictionaryTest.cs
This commit moves the definition of the `field` property up to
the parent class, DictionaryGetFieldResponse.  Prior to this
commit it was defined on each individual subclass, meaning you
could only access it within a type guard conditional.  This way,
you can access it regardless of whether your response was a Hit,
Miss, or Error.  This allows us to simplify some things in the
Dictionary example.
=> fix: Improve accessibility of field name in DictionaryGetField response

src/Momento.Sdk/Responses/CacheDeleteResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryFetchResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldsResponse.cs, src/Momento.Sdk/Responses/CacheGetResponse.cs, src/Momento.Sdk/Responses/CacheListFetchResponse.cs, src/Momento.Sdk/Responses/CacheListPopBackResponse.cs, src/Momento.Sdk/Responses/CacheListPopFrontResponse.cs, src/Momento.Sdk/Responses/CacheSetFetchResponse.cs, src/Momento.Sdk/Responses/CreateCacheResponse.cs, src/Momento.Sdk/Responses/DeleteCacheResponse.cs, src/Momento.Sdk/Responses/FlushCacheResponse.cs, src/Momento.Sdk/Responses/ListCachesResponse.cs
Previously many of the data response examples did not include a branch
for miss. We add those in.
Also we found the control operations were missed branches. We add
those in as well.
=> docs: fix response handling examples to account for all branches

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/ICacheClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/Utils.cs, tests/Integration/Momento.Sdk.Tests/ListTest.cs
- Added additional params, `startIndex` and `endIndex` to the `listFetch` API
- Added tests for the new params
Closes #410
=> chore: add `startIndex` and `endIndex` to `listFetch` API

src/Momento.Sdk/Auth/Utils.cs, src/Momento.Sdk/Internal/ExtensionMethods/DictionaryExtensions.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/CacheDictionaryFetchResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldsResponse.cs
In order to support customers running older versions of the .NET
runtime, we lower the target framework. This requires only minor
changes to the code to account for missing implementations. These
include: `Convert.TryFromBase64String` and a `Dictionary` constructor
that takes `IEnumerable<KeyValuePair<TKey, TValue>>`.
Work towards: https://github.com/momentohq/dev-eco-issue-tracker/issues/317
=> feat: lower target framework to netstandard2.0

src/Momento.Sdk/Config/Configurations.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs
Adds a configuration optimized for Lambda environments. This is the
same as the `InRegion.Default` config but also eagerly connects the
client. This avoids the cold start penalty from before where we
established the connection on the first request, leading to
first-request timeouts.
=> feat: add lambda configuration

tests/Integration/Momento.Sdk.Tests/CacheEagerConnectionTest.cs
We have a test that asserts that the CacheClient can still be
constructed even if it's in EagerConnection mode and the Ping
fails.  That logs a scary looking warning during the int test
runs.  This commit adds a println to let future developers
know that they don't need to be worried by it :)
=> chore: print a warning before eager connection failure test

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, .github/workflows/on-push-to-release-branch.yaml, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, tests/Integration/Momento.Sdk.Tests/Momento.Sdk.Tests.Integration.csproj, tests/Unit/Momento.Sdk.Tests/Momento.Sdk.Tests.Unit.csproj
Because .NET Framework does not support gRPC over HTTP/2, we fall back
to using gRPC for those older versions. To do this we:
1. Add another target framework for the library, `net461`. This is the
lowest .NET Framework version also supported by `netstandard2.0`.
2. Conditional on a `net461` build, link the gRPC-Web client
dependency.
3. Conditional on a `net461` build, use a gRPC-Web `HttpHandler` for
the control and data gRPC channels.
4. Update the test projects to exercise the `net461` build as well.
closes: https://github.com/momentohq/dev-eco-issue-tracker/issues/317
=> feat: support .NET Framework 4.61+ using gRPC-Web

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/ICacheClient.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/CacheUpdateTtlResponse.cs, tests/Integration/Momento.Sdk.Tests/TtlTest.cs
This adds the command `UpdateTtl`, which unconditionally overwrites
the TTL of an item in the cache. Bumps protos version; adds the
command, documentation, and integration tests.
=> feat: implement `UpdateTtl` command

tests/Integration/Momento.Sdk.Tests/DictionaryTest.cs, tests/Integration/Momento.Sdk.Tests/ListTest.cs, tests/Integration/Momento.Sdk.Tests/SetTest.cs, tests/Integration/Momento.Sdk.Tests/TtlTest.cs, tests/Integration/Momento.Sdk.Tests/Utils.cs
When running these integration tests in region in an aws account, we were seeing flaky results. It seems to be due to the fact that we return keys/values even slightly after they are ttl'd out. This pr relaxes some of the integration test timeouts to allow some leniency in their timeouts/ttls.
Testing in fargate, these changes are passing now
=> fix: update int test ttls to be more lenient

src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs
- feat: use web prefix for endpoints when using gRPC-web
- feat: use appropriate agent header moniker when using gRPC-web
closes #442
=> feat: update agent header and endpoint for gRPC web

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/ICacheClient.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/CacheDictionaryLengthResponse.cs, tests/Integration/Momento.Sdk.Tests/DictionaryTest.cs
Add support for Dictionary Length API
- Integration tests:
- `TEST_CACHE_NAME="test-cache" dotnet test -f net6.0 --filter "DictionaryLengthAsync_HappyPath"`
- `TEST_CACHE_NAME="test-cache" dotnet test -f net6.0 --filter "DictionaryLengthAsync_DictionaryIsMissing"`      
closes #447
=> feat: Add support for Dictionary Length API

src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Responses/CacheListFetchResponse.cs, src/Momento.Sdk/Responses/CacheListLengthResponse.cs, src/Momento.Sdk/Responses/CacheListPopBackResponse.cs, src/Momento.Sdk/Responses/CacheListPopFrontResponse.cs, src/Momento.Sdk/Responses/CacheListRemoveValueResponse.cs, src/Momento.Sdk/Responses/CacheListRetainResponse.cs, tests/Integration/Momento.Sdk.Tests/ListTest.cs
- Add ListLength to list modification apis
- Reformat integration tests to cover ListLength methods
Adding checked after casting the `response.Found.Length` (which return a uint) to int because: uint in public APIs is discouraged in .NET as it is not CLS compliant
`make test-net6` to run the entire suite
closes #414
=> feat: Add ListLength to list modification apis

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, tests/Integration/Momento.Sdk.Tests/CacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/Utils.cs
Our tests currently require a TEST_CACHE environment variable, which
is not really useful and sets a pattern that other SDKs may need
to require this too in order to standardize on a way to launch them
(for example in the SDK canaries). The JS SDK does not work properly
if you set that environment variable, because it is intended for use
when running against a local mr2.
This commit removes the env var and dynamically creates a cache
name to use for the tests.
=> chore: get rid of TEST_CACHE environment variable

src/Momento.Sdk/Config/Middleware/ExperimentalMetricsCsvMiddleware.cs, src/Momento.Sdk/Config/Middleware/ExperimentalMetricsLoggingMiddleware.cs, src/Momento.Sdk/Config/Middleware/ExperimentalMetricsMiddleware.cs
Add abstract middleware that captures metrics for each grpc request.
Add metrics middleware implementation that writes the metrics to a CSV.
Add metrics middleware implementation that logs the metrics.
=> feat: Add experimental metrics logging middleware

CONTRIBUTING.md, examples/MomentoLoadGen/Program.cs, examples/MomentoLoadGen/README.md
Updated readme, minor cleanup, and added more stats to loadgen
=> chore: updated readme and added more stats to loadgen

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Internal/Middleware/FairAsyncSemaphore.cs, src/Momento.Sdk/Internal/Middleware/MaxConcurrentRequestsMiddleware.cs, tests/Integration/Momento.Sdk.Tests/CacheEagerConnectionTest.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs
The dotnet SDK exposes two configurations to clients ```MaxConcurrentRequests``` and ```MinNumGRPCChannels```. Both these configurations essentially impacts the number of connections that we open to the Momento server. Before this PR, a user could provide 10 gRPC channels as minimum, and 20 as maxConn, assuming that 20 maxConn will be a global setting. However, because how we wire our middleware, each channel would get 20 max concurrent requests as the setting. This PR resolves the conflict between the interplay of these settings (more details inline on code comments).
=> fix: fix configuration settings for maxConn and gRPC channels

CONTRIBUTING.md, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/TestCacheClient.cs
Momento doesn't offer strict read-after-write consistency, despite
often appearing to. That's an implicit test dependency on the
subjective latency of the test runner, however. By relaxing the
expectation to some small window for a get() response to settle,
the tests should be a little more reliable.
I wrapped CacheClient in a new TestCacheClient implementation of
ICacheClient. Code for delegation to the TestCacheClient's client
field was generated by Visual Studio. This new implementation is
the new CacheClientFixture client implementation.
Also minorly updated some docs.
=> chore: Relax integration test timing assertions

.github/workflows/on-push-to-release-branch.yaml, src/Momento.Sdk/Momento.Sdk.csproj
This commit makes a small change to the csproj file that allows us
to specify DefineConstants=USE_GRPC_WEB for any target framework.
That allows us to do a netframework20 + grpc-web build, which is
necessary for compatibility with the Unity platform.
We also add a step to the release action to do a build with this
configuration, and attach it to the github release.
=> feat: Add build for Unity platform

.github/workflows/build.yaml, src/Momento.Sdk/Config/ITopicConfiguration.cs, src/Momento.Sdk/Config/TopicConfiguration.cs, src/Momento.Sdk/Config/TopicConfigurations.cs, src/Momento.Sdk/Config/Transport/ITopicTransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTopicTransportStrategy.cs, src/Momento.Sdk/ITopicClient.cs, src/Momento.Sdk/Internal/LoggingUtils.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/TopicMessage.cs, src/Momento.Sdk/Responses/TopicPublishResponse.cs, src/Momento.Sdk/Responses/TopicSubscribeResponse.cs, src/Momento.Sdk/TopicClient.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/Momento.Sdk.Tests.Integration.csproj, tests/Integration/Momento.Sdk.Tests/TopicTest.cs, tests/Integration/Momento.Sdk.Tests/xunit.runner.json
Add the initial topics implementation. The entry point is TopicClient, which contains the publish and subscribe methods. Subscribe returns an IAsyncEnumerable<TopicMessage> that can be iterated over to read from the topic.
=> feat: add topics

src/Momento.Sdk/Auth/AccessControl/DisposableToken.cs, src/Momento.Sdk/Auth/AccessControl/DisposableTokenScope.cs, src/Momento.Sdk/Auth/AccessControl/DisposableTokenScopes.cs, src/Momento.Sdk/Auth/AccessControl/ExpiresIn.cs, src/Momento.Sdk/Auth/AccessControl/Permissions.cs, src/Momento.Sdk/Auth/EnvMomentoTokenProvider.cs, src/Momento.Sdk/Auth/ICredentialProvider.cs, src/Momento.Sdk/Auth/StringMomentoTokenProvider.cs, src/Momento.Sdk/Auth/Utils.cs, src/Momento.Sdk/AuthClient.cs, src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/Config/AuthConfiguration.cs, src/Momento.Sdk/Config/AuthConfigurations.cs, src/Momento.Sdk/Config/IAuthConfiguration.cs, src/Momento.Sdk/Config/Transport/IAuthTransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticAuthTransportStrategy.cs, src/Momento.Sdk/IAuthClient.cs, src/Momento.Sdk/Internal/AuthGrpcManager.cs, src/Momento.Sdk/Internal/LoggingUtils.cs, src/Momento.Sdk/Internal/OldDotNetVersionsRecordWorkaround.cs, src/Momento.Sdk/Internal/ScsTokenClient.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/GenerateDisposableTokenResponse.cs, tests/Integration/Momento.Sdk.Tests/AuthClientTest.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Unit/Momento.Sdk.Tests/Auth/AccessControl/DisposableTokenScopeTest.cs, tests/Unit/Momento.Sdk.Tests/Momento.Sdk.Tests.Unit.csproj, tests/Unit/Momento.Sdk.Tests/MomentoXunitFramework.cs
This commit adds an auth client that is currently solely responsible for generating disposable tokens.
=> feat: add auth client

src/Momento.Sdk/Internal/LoggingUtils.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs
Instead of returning an error message, attempt to reconnect to a topic on error by remaking the subscription.
=> feat: reconnect topic subscriptions on error

examples/DocExampleApis/DocExampleApis.csproj, examples/DocExampleApis/Program.cs, src/Momento.Sdk/Auth/AccessControl/DisposableTokenScopes.cs
Addresses [#453](https://github.com/momentohq/dev-eco-issue-tracker/issues/453) by adding code snippet for `GenerateDisposableToken` that will be pulled into the dev docs. This snippet can be used [here](https://docs.momentohq.com/develop/authentication/tokens) and [here](https://docs.momentohq.com/develop/api-reference/auth#generatedisposabletoken-api).
Addresses [#459](https://github.com/momentohq/dev-eco-issue-tracker/issues/459) by adding code snippets for instantiating a topic client, publishing to a topic, and subscribing to a topic. These examples will be used [on this page](https://docs.momentohq.com/develop/api-reference/topics).
=> chore: add topics and disposable token code snippets for dev docs

examples/DocExampleApis/DocExampleApis.csproj, examples/DocExampleApis/Program.cs
=> chore: update dev docs example to use new predefined disposable token scope function

src/Momento.Sdk/Responses/GenerateDisposableTokenResponse.cs
This commit overrides `ToString` for the `GenerateDisposableTokenResponse.Success` class. Printing an object of this type now displays a truncated version of the token (e.g., `eyJlbmRwb2...03dVBYWSJ9`).
=> chore: add ToString override for disposable token

src/Momento.Sdk/Exceptions/InternalServerException.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Responses/TopicSubscribeResponse.cs, tests/Integration/Momento.Sdk.Tests/AuthClientTopicTest.cs
Make the internal subscribe method get the first message and check it to ensure the stream can be read. Without this, certain topic errors won't be caught until the user attempts to iterate over the topic stream.
Break out of the subscription when it receives a permission or authentication error. These cannot be recovered from, so there is no point in reconnecting. This covers the case of a token that expires while being used to read a topic.
Enable the auth client topic tests covering cases that should return an error on subscribe.
=> chore: return an error from the subscribe method for a bad stream

tests/Integration/Momento.Sdk.Tests/AuthClientTopicTest.cs
Commenting this test out to prevent breaking build pipelines, until
we have time to root cause it.
=> chore: temporarily comment out flaky test

tests/Integration/Momento.Sdk.Tests/TtlTest.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs
Properly delete indexes in the MVI control tests.
Give intermittently failing TTL test more generous timing and add failure messages.
=> fix: clean up after MVI control tests

tests/Integration/Momento.Sdk.Tests/AuthClientCacheTest.cs, tests/Integration/Momento.Sdk.Tests/AuthClientTopicTest.cs, tests/Integration/Momento.Sdk.Tests/CacheDataTest.cs, tests/Integration/Momento.Sdk.Tests/DictionaryTest.cs, tests/Integration/Momento.Sdk.Tests/ListTest.cs, tests/Integration/Momento.Sdk.Tests/SetTest.cs, tests/Integration/Momento.Sdk.Tests/TtlTest.cs
Addresses https://github.com/momentohq/oncall-tracker/issues/3051
Updated all `Assert.True` statements to include a message to print upon failure. Also uncomments the flaky test so it's back in now.
=> chore: make sure all assert.true statements include message on failure

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/PreviewVectorIndexClient.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Remove incorrect plural from DeleteIndexesAsync. The preview vector index client has an unstable api warning, so this name change is possible.
Remove temp test that was used to clear out indexes on the test account.
=> chore: rename DeleteIndexesAsync to DeleteIndexAsync

src/Momento.Sdk/Responses/Vector/SearchHit.cs, src/Momento.Sdk/Responses/Vector/SearchResponse.cs
To align with the scoreThreshold option in search, and for clarity in that the search hits are not ordered by distance (which is lower or better), but by score (which could be higher or better, or a blend of multiple things), we rename the distance property to score.
=> chore: rename MVI search hit Distance property to Score

src/Momento.Sdk/Internal/VectorIndexControlClient.cs, src/Momento.Sdk/Responses/Vector/IndexInfo.cs, src/Momento.Sdk/Responses/Vector/ListIndexesResponse.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs
Change the data that ListIndexesAsync returns from a list of index names to a list of IndexInfo object containing the names. We will add more fields in the future.
=> chore: change ListIndexesAsync return to a list of IndexInfo

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/PreviewVectorIndexClient.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Add score threshold to the MVI search method.
Update the protos and change 'distance' to 'score' in internal search response.
=> feat: add score threshold to MVI search

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/Internal/VectorIndexDataGrpcManager.cs, src/Momento.Sdk/PreviewVectorIndexClient.cs, src/Momento.Sdk/Responses/Vector/SearchAndFetchVectorsResponse.cs, src/Momento.Sdk/Responses/Vector/SearchHit.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Add a new version of the MVI search method that returns the vectors with the hits.
Paramaterize the search integration tests so that they cover both search methods.
=> feat: Add MVI SearchAndFetchVectors method

src/Momento.Sdk/Internal/VectorIndexControlClient.cs, src/Momento.Sdk/Momento.Sdk.csproj
Updates MVI list and create indexes backend for latest changes. Updates protos but developer-facing API remains otherwise the same.
=> chore: update mvi control plane for create and list indexes protos

tests/Integration/Momento.Sdk.Tests/Utils.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Refactor integration tests to use `Disposable` pattern throughout. A helper class creates an index on initialization and cleans up on disposal. Integration test authors then wrap code that needs an index in a `using` block. Upon exit of the `using` block, the index will be deleted.
=> fix: clean up vector indexes in integration tests

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/Internal/ExtensionMethods/DictionaryExtensions.cs, src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/Internal/VectorIndexDataGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/PreviewVectorIndexClient.cs, src/Momento.Sdk/Requests/Vector/Item.cs, src/Momento.Sdk/Responses/Vector/GetItemBatchResponse.cs, src/Momento.Sdk/Responses/Vector/GetItemMetadataResponse.cs, src/Momento.Sdk/Responses/Vector/SearchHit.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Implements MVI `GetItemBatchAsync` and `GetItemMetadataBatchAsync` methods, response types, and adds integration tests. Also extracts metadata dictionary equality and hash code to a central extension method.
=> feat: implement mvi get item and get item metadata methods

examples/DocExampleApis/Program.cs, src/Momento.Sdk/Auth/AccessControl/DisposableToken.cs, src/Momento.Sdk/Auth/AccessControl/DisposableTokenScope.cs, src/Momento.Sdk/Auth/AccessControl/DisposableTokenScopes.cs, src/Momento.Sdk/Auth/AccessControl/ExpiresIn.cs, src/Momento.Sdk/Auth/AccessControl/Permissions.cs, src/Momento.Sdk/AuthClient.cs, src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/IAuthClient.cs, src/Momento.Sdk/Internal/AuthGrpcManager.cs, src/Momento.Sdk/Internal/ScsTokenClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/GenerateDisposableTokenResponse.cs, tests/Integration/Momento.Sdk.Tests/AuthClientCacheTest.cs, tests/Integration/Momento.Sdk.Tests/AuthClientTopicTest.cs
Fixes warnings in test and build, including: improper order of arguments in asserts and lots of missing documentation.
=> chore: fix warnings

tests/Integration/Momento.Sdk.Tests/Utils.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
In order to debug leaking indexes, we add a unique suffix for each
index name. That way we can inspect and identify patterns in leaked
resources.
=> test: add unique, identifying suffix to each integration test index

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/Internal/VectorIndexDataGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/PreviewVectorIndexClient.cs, src/Momento.Sdk/Responses/Vector/CountItemsResponse.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Adds MVI count items, which returns the number of items in a vector
index. In the event an index does not exist, the response is a
`NOT_FOUND` error. That way we distinguish between an empty index that
does exist vs an index that does not exist.
This PR adds the response type, method, documentation, and integration
tests.
=> feat: implement mvi count items command

src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/Momento.Sdk.csproj
We are in the process of migrating MVI delete item batch, get item batch, and get item metadata batch to use a filter expression to select items to delete (get) as opposed to a list of id's. For convenience, we will still allow users to select items with a list of id's from the top level methods. This PR migrates the backend.
As part of the migration we are also moving away from the hit/miss pattern for get item batch and get item metadata batch response messages. While the hit/miss pattern made sense for when we only selected items by id, it no longer makes sense for when a user supplies a general filter expression. What's more, previously when we read the hit/miss responses, we built a dictionary containing only the hits, so the distinction wasn't as important.
In future PRs we will add …
=> refactor: use mvi filter fields for get/delete items

src/Momento.Sdk/IPreviewVectorIndexClient.cs, src/Momento.Sdk/Internal/VectorIndexDataClient.cs, src/Momento.Sdk/PreviewVectorIndexClient.cs
To standardize how we select items in get item batch, get item
metadata batch, and delete item batch, we use the term filter in
methods, whether selecting by ids or filter expression.
=> refactor: rename mvi parameter ids to filter on get/delete item batch

.github/workflows/build.yaml, examples/DictionaryExample/Program.cs, examples/DisposableTokens/Program.cs, examples/DisposableTokens/README.md, examples/DocExampleApis/Program.cs, examples/MomentoApplication/Program.cs, examples/MomentoApplication/README.md, examples/MomentoFSharpApplication/Program.fs, examples/MomentoLoadGen/Program.cs, examples/MomentoLoadGen/README.md, examples/MomentoUsage/Program.cs, examples/MomentoUsage/README.md, examples/TopicExample/Program.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs
Prior to this commit, if we failed to eagerly connect, we were not logging any information about
the reason. This commit adds the exception to the log. Tested by disabling my network connection
and verified it includes all the relevant info.
Also updates places in example code where we were still using MOMENTO_AUTH_TOKEN for env var names,
now that we have standardized on MOMENTO_API_KEY.
=> fix: include exception in log message when eager connection fails; update env vars to MOMENTO_API_KEY

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Exceptions/ConnectionException.cs, src/Momento.Sdk/Exceptions/SdkException.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, tests/Integration/Momento.Sdk.Tests/CacheEagerConnectionTest.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs
This commit makes the following changes:
* Stop trying to do the eager connection stuff in the constructor
of the CacheClient, because this can have surprising side effects,
e.g. if we want to throw an error on failure.
* Remove the associated Configuration settings since we no longer
support eager connections at construction time.
* Add a new factory function, CacheClient.CreateAsync, which is the
new mechanism for create a client with an eager connection. This
matches the pattern we established in the other SDKs that support
eager connections.
* If the eager connection fails, we now throw a new ConnectionError
rather than just logging a warning. This gives the consumer
the ability to decide how to handle this type of error rather than
us just swallowing it and removing their choice. In …
=> feat: async factory function for eager connections

src/Momento.Sdk/Internal/AuthGrpcManager.cs, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/Internal/VectorIndexControlGrpcManager.cs, src/Momento.Sdk/Internal/VectorIndexDataGrpcManager.cs
By default, grpc allows the server to receive messages up to 4mb in size. This sets the default to 5mb.
Will DRY up the code in a follow up PR that will also add keepalive settings, as per https://github.com/momentohq/dev-eco-issue-tracker/issues/658
=> fix: add support for item sizes up to 5mb

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, Makefile, src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/IConfiguration.cs, src/Momento.Sdk/Config/Transport/IGrpcConfiguration.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/SocketsHttpHandlerOptions.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/ITopicClient.cs, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/LoggingUtils.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/TopicMessage.cs, src/Momento.Sdk/Responses/TopicPublishResponse.cs, src/Momento.Sdk/Responses/TopicSubscribeResponse.cs, src/Momento.Sdk/TopicClient.cs, tests/Integration/Momento.Sdk.Tests/AuthClientTopicTest.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/Momento.Sdk.Tests.Integration.csproj, tests/Unit/Momento.Sdk.Tests/Momento.Sdk.Tests.Unit.csproj
1. Add SocketHttpHandler config options and plumb through.
2. Set Lambda config to use `SocketHttpHandler.PooledConnectionIdleTimeout` 
of 6 minutes. 
3. Add target frameworks for .NET 6.0 and bump target framework net461
to net462 for async iterator support.
In `Grpc.Net.Client`, the default HttpHandler on .NET runtimes .NET
5.0 or greater is `SocketsHttpHandler`. In this PR we create a new
options class to encapsulate customizations to the handler, most
importantly the pooled connection timeout and whether to enable
multiple http connections.
The default value for the idle connection timeout is 1 minute. We find
this too strict in lambda environments, where the container may freeze
and thaw in greater than 1 minute spans but less than the server
timeout (5 minutes as of writing). …
=> feat: adds customization options for SocketsHttpHandler

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/IConfiguration.cs
Previously we had added a copy factory to `Configuration` to change
`SocketHttpHandlerOptions`. While tihs was for the convenience of the
`Configurations` code, this exposed a low level detail to the top
level of `Configuration`, which is undesirable.
We remove that in this PR. Since the previous code using it was wholly
encapsulated in `Configurations`, this does not break other code.
=> chore: remove socket option modifier from configuration

src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs
In some runtimes, even though `SocketsHttpHandler` is included in the
runtime it is not supported. Thus we add guards to test for this and
let the gRPC client fall back to a supported one.
=> chore: add is supported guard for SocketsHttpHandler

README.md, examples/DictionaryExample/README.md, examples/DisposableTokens/README.md, examples/MomentoApplication/README.md, examples/MomentoLoadGen/README.md, examples/MomentoUsage/README.md, examples/README.md, examples/TopicExample/README.md
Clean up readme instructions from "auth token from CLI" to "api key from console"
=> chore: update readmes to use api key from console instead of auth token from cli

README.template.md
#544 seemed to break the readme generator on push to main.
This PR fixes the broken link in the readme using the template instead of editing the readme directly.
=> chore: update readme template to fix broken link instead of readme directly

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, src/Momento.Sdk/Momento.Sdk.csproj
Since we bumped the minimum .NET Framework build version from 4.61 to
4.62, we gained access to an Http/2 handler for .NET
Framework. Because 4.61 did not have an Http/2 handler, we had to
resort to gRPC-Web. Now we only need gRPC-Web for the Unity build.
In order to exercise the gRPC-Web build, we add that to the testing
matrix.
=> feat: drop grpc-web for .NET 4.62 build.

.github/workflows/on-push-to-main-branch.yaml
Saw a [failure](https://github.com/momentohq/client-sdk-dotnet/actions/runs/8179952682/job/22367041811) on the readme generator job. Realized there was a checkout step missing.
=> fix: add missing step to workflow file for readme generator

tests/Integration/Momento.Sdk.Tests/SetTest.cs
These tests had previously been disabled because they would
cause canary failures in cells where the server changes hadn't
yet been deployed. This commit re-enables them.
=> chore: re-enable setSample tests

src/Momento.Sdk/CacheClient.cs
In order to clean up resources on a failed eager connection (`Ping`)
RPC, we dispose the cache client on exception in
`CacheClient::CreateAsync`.
=> fix: dispose cache client when eager connection fails

src/Momento.Sdk/CacheClient.cs
To preserve the original stack trace, one needs to use a `throw;`
statement, not re-throw the original exception. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/exception-handling-statements
=> fix: properly re-throw caught exception in eager connection code

src/Momento.Sdk/Momento.Sdk.csproj
This addresses regressions we saw when spawning many new
connections. Possibly fixed by https://github.com/grpc/grpc-dotnet/pull/2422
=> feat: bump grpc.net.client to v2.63.0

src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs
```
agent: dotnet:1.0.0.0, runtime-version: .NET 6.0.11
```
The agent is showing up as `1.0.0.0` because inside of our sdk `.csproj` we do not have a `Version` property. This property gets set when we actually cut the release. I manually set the `.csproj` `Version` property to `2.2.2` and the agent shows up as `dotnet:2.2.2.0`
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/887
=> feat: onetime headers for agent and runtime-version

src/Momento.Sdk/Internal/Middleware/HeaderMiddleware.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/ScsTokenClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs
In order to standardize the agent and runtime-version headers, we
lowercase the header names.
=> chore: lowercase agent and runtime-headers

.github/workflows/build.yaml, .github/workflows/on-push-to-main-branch.yaml, .github/workflows/on-push-to-release-branch.yaml, CONTRIBUTING.md, Makefile
Simplifies the `Makefile` in the following ways:
- Refactors the core commands `build` and `test` to be OS-conditional. When we detect Windows, we build and test against not just .NET 6.0 but also .NET Framework, the latter of which is Windows-only. This way a developer or consumer of the `Makefile` does not need to specify an OS-specific target (`test-dotnet-framework` vs `test-dotnet-6`)
- Adds a make variable for building with gRPC web. The GitHub Actions tested against each OS, Framework, and with/without gRPC web. We make this easier by adding a `GRPC_WEB` variable. To build with gRPC web, run `make GRPC_WEB=true build`.
- Includes logging options previously only in GitHub actions.
- Refactors GitHub Actions to invoke the Makefile targets to build and test. When on Windows, `build` …
=> chore: refactor makefile and actions

Makefile, tests/Integration/Momento.Sdk.Tests/Auth/AuthClientCacheTest.cs, tests/Integration/Momento.Sdk.Tests/Auth/AuthClientTopicTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Control/CacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/CacheEagerConnectionTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/CacheScalarTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/DictionaryTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/ListTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/SetTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/Data/TtlTest.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/TestBase.cs, tests/Integration/Momento.Sdk.Tests/TestCacheClient.cs, tests/Integration/Momento.Sdk.Tests/Topics/Data/TopicTest.cs, tests/Integration/Momento.Sdk.Tests/Usings.cs, tests/Unit/Momento.Sdk.Tests/Auth/CredentialProviderTest.cs, tests/Unit/Momento.Sdk.Tests/CacheClientConstructorTest.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs, tests/Unit/Momento.Sdk.Tests/Internal/ExtensionMethods/ByteArrayExtensionsTest.cs, tests/Unit/Momento.Sdk.Tests/Internal/ExtensionMethods/StringExtensionsTest.cs, tests/Unit/Momento.Sdk.Tests/Responses/CacheGetResponseTest.cs
This PR introduces to changes:
1. Groups the tests by integration vs unit tests first, with namespaces; then by service (cache, topics, auth); then by control vs data. This is to ease filtering by the Makefile targets.
2. Adds Makefile targets for each of the endpoints (cache, control, token, storage). Because we test Windows-only builds as well, we make each of these OS-conditional.
A caller wishing to run all the tests can run `make test`. On Windows this will run against both .NET Framework 4.62 (which is Windows only) as well as .NET 6.0. On Linux or Mac OS this will only run against .NET 6.0.
Similarly, a caller wishing to run only the control endpoint tests can run `make test-control-endpoint` (or `test-cache-endpoint`, `test-token-endpoint`, `test-storage-endpoint` for other …
=> refactor: organize tests by endpoint and provide endpoint-specific make targets

Makefile, tests/Integration/Momento.Sdk.Tests/Cache/CacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/CacheEagerConnectionTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/CacheScalarTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/DictionaryTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/ListTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/SetTest.cs, tests/Integration/Momento.Sdk.Tests/Cache/TtlTest.cs, tests/Integration/Momento.Sdk.Tests/Topics/TopicTest.cs
Previously we organized the make targets by endpoint. This isn't
granular enough to test when some services aren't deployed at an
endpoint (eg leaderboards in the cache endpoint).
With this change we test by service. Because of this we simplify the
test organization by not grouping by control vs data.
=> refactor: organize targets by service not endpoint

.github/workflows/on-push-to-release-branch.yaml, src/Momento.Sdk/Momento.Sdk.csproj
Add a new Momento.Sdk.Web artifact that uses gRPC-Web so that users without access to HTTP 2.0 can use the SDK. Building with the USE_GRPC_WEB will generate the new Momento.Sdk.Web.dll. Note that this will affect the unity build as well.
Add a pack and publish step to push the new artifact to nuget.
=> feat: Add a separate web SDK for clients without HTTP 2.0

tests/Integration/Momento.Sdk.Tests/Cache/DictionaryTest.cs
The test now outputs the actual keys and values stored in the dictionary like below example:
```
Hit Response Dictionary Contents:
Key: 60-7E-FC-0E-86-2F-C8-4D-AE-BD-1B-18-FB-1C-18-CE | Value: 87-4C-1A-5B-61-2A-DA-47-A4-26-3A-F3-40-65-68-55
Key: 9F-24-B9-EB-39-84-B4-43-A4-23-75-B4-DF-0C-54-CE | Value: 61-53-2C-CD-04-4D-56-49-8D-73-7D-33-B2-A6-A6-88
```
=> chore: add better logging for dictionary tests

src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Responses/Topic/ITopicEvent.cs, src/Momento.Sdk/Responses/Topic/TopicEvent.cs, src/Momento.Sdk/Responses/Topic/TopicMessage.cs, src/Momento.Sdk/Responses/Topic/TopicSubscribeResponse.cs, src/Momento.Sdk/Responses/Topic/TopicSystemEvent.cs, tests/Integration/Momento.Sdk.Tests/Topics/TopicTest.cs
Introduces an interface `ITopicEvent` which covers both normal
messages (`TopicMessage`) and system events (`TopicSystemEvent`). We
refactor the internals of the stream to be over `ITopicEvent`s, so
that we can filter to just `TopicMessage` (as is implemented
currently) or pass through all events in an event enumerable.
To enumerate over all events in the stream, call `GetAllEventsAsyncEnumerable`,
or `WithCancellationForAllEvents`.
This largely parallels the existing enumerator over messages only. See the
integration tests for an example usage.
=> feat: add an topic event enumerable

examples/DocExampleApis/DocExampleApis.csproj, examples/DocExampleApis/Program.cs
Use the "all events" API in the doc examples.
=> chore: update doc example apis to use advanced api

examples/TopicHeartbeatExample/README.md
Adds a README for the new topic heartbeat example. This was omitted by mistake from the previous PR.
=> chore: add README for topic heartbeat example

tests/Integration/Momento.Sdk.Tests/Auth/AuthClientTopicTest.cs, tests/Integration/Momento.Sdk.Tests/Topics/TopicTest.cs, tests/Integration/Momento.Sdk.Tests/Utils.cs
While investigating some canary failures, discovered that the auth topics tests were reusing topic names.
Added a new util function to ensure unique topic names are used in all topics tests.
=> chore: ensure tests use unique topic names

src/Momento.Sdk/Exceptions/CacheExceptionMapper.cs, src/Momento.Sdk/Exceptions/LimitExceededException.cs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1039
Passes the `RpcException` to the `LimitExceededError` so it can parse the trailer metadata or error details to determine the most specific error message wrapper to return.
=> chore: improve resource exhausted error message

src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Momento.Sdk.csproj
Upgrades to latest protos and adds using statements for
`Momento.Protos.Common`.
The previous version of `Momento.Protos` we used here pre-dated where
we split several messages to `common.proto`. In order to isolate the
changes, we upgrade the dependency and add the missing `using`s here.
=> feat: upgrade protos and fix usings

src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Responses/Topic/TopicMessage.cs, src/Momento.Sdk/Responses/Topic/TopicSystemEvent.cs, tests/Integration/Momento.Sdk.Tests/Topics/TopicTest.cs
Changes TopicItem and TopicSystemEvent to store the sequence number/page as `ulong`. This removes a checked cast under the hood.
Also plumbs through `resumeAtTopicSequenceNumber` (page) to the subscription wrapper.
I tested these changes on both topics examples successfully without any changes on the example side.
=> feat: use ulong and topics and plumb through `resumeAt` subscription arguments

src/Momento.Sdk/Internal/Retry/DefaultRetryEligibilityStrategy.cs
Bring the list of retryable functions up to date.
Replace GetHashCode with a version that matched the equals method.
Fix misc warnings.
=> chore: update list of retryable gRPC functions

src/Momento.Sdk/Internal/GrpcManager.cs
- On reasearching [grpc-dotnet behavior](https://github.com/googleapis/gax-dotnet/commit/ac695425d9f25314ab60316d72f1d4eed57ef581#diff-22029e198e06de6cfa24f7f6ba052ee14aa03dc179776e5e6f5f065a7f64c9b9R31), I found that the grpc service config is by default disabled. But, this pr still explicitly sets it to null to disable the grpc service config. 
```
$ sudo tcpdump -i any -vvv port 53 | grep -i cache.cell-alpha-dev.preprod.a.momentohq.com          
tcpdump: data link type PKTAP
tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), snapshot length 524288 bytes
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.51445: [udp sum ok] 30325 q: A? control.cell-alpha-dev.preprod.a.momentohq.com. 2/0/0 control.cell-alpha-dev.preprod.a.momentohq.com. [5m] CNAME …
```
=> fix: disable dynamic DNS service config

src/Momento.Sdk/Auth/EnvMomentoTokenProvider.cs, src/Momento.Sdk/Auth/ICredentialProvider.cs, src/Momento.Sdk/Auth/MomentoLocalProvider.cs, src/Momento.Sdk/Auth/StringMomentoTokenProvider.cs, src/Momento.Sdk/AuthClient.cs, src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/Internal/AuthGrpcManager.cs, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/GrpcManager.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/ScsTokenClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/TopicClient.cs, tests/Unit/Momento.Sdk.Tests/Auth/MomentoLocalProviderTest.cs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1193
- Adds `MomentoLocalProvider`, an implementation of `ICredentialProvider`, to connect clients to momento-local servers.
- Piped the credential provider through to the base `GrpcManager` to be able to check whether to use secure endpoints (SSL channel credentials and https) or insecure because momento-local uses insecure connections).
- Adds unit tests for MomentoLocalProvider
Tested locally and confirmed the `MomentoUsage` example can create a `MomentoLocalProvider` and connect to a running momento-local docker container.
=> feat: add CredentialProvider for momento-local connections

src/Momento.Sdk/Config/Retry/MomentoRpcMethod.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/TestRetryMetricsCollector.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/TestRetryMetricsCollectorTest.cs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1191
Adds the MomentoRpcMethod enum for specifying Momento RPCs in the metrics collector (and in middleware in a future PR).
Adds the TestRetryMetricsCollector class and unit tests to prepare for writing momento-local tests exercising cache retry strategies.
=> feat: add MomentoRpcMethod enum and TestRetryMetricsCollector

src/Momento.Sdk/Auth/MomentoLocalProvider.cs, tests/Unit/Momento.Sdk.Tests/Auth/MomentoLocalProviderTest.cs
Addressing a previous [PR comment](https://github.com/momentohq/client-sdk-dotnet/pull/598#discussion_r2004415537)
=> chore: remove unnecessary MomentoLocalProvider non-default constructor

src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Retry/FixedTimeoutRetryStrategy.cs, src/Momento.Sdk/Config/Retry/IRetryStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/Middleware/RetryMiddleware.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Internal/ScsTokenClient.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/Utils.cs, tests/Integration/Momento.Sdk.Tests/Retry/FixedTimeoutRetryStrategyTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/MomentoLocalMiddlewareTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/TestRetryMetricsCollectorTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/MomentoLocalMiddleware.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/MomentoRpcMethod.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/TestRetryMetricsCollector.cs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1195
Adds fixed timeout retry strategy (used [JS](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/client-sdk-nodejs/src/config/retry/fixed-timeout-retry-strategy.ts) and [Java](https://github.com/momentohq/client-sdk-java/blob/main/momento-sdk/src/main/java/momento/sdk/retry/FixedTimeoutRetryStrategy.java) implementations for reference).
Adds momento-local tests exercising the fixed timeout strategy.
=> feat: fixed timeout retry strategy and tests

src/Momento.Sdk/Config/Retry/ExponentialBackoffRetryStrategy.cs, tests/Integration/Momento.Sdk.Tests/Retry/ExponentialBackoffRetryStrategyTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/FixedCountRetryStrategyTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/MomentoLocalMiddleware.cs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1195
Adds ExponentialBackoffRetryStrategy and tests based on the JS, Java, and Go implementations.
Also found a bug in how the MomentoLocalMiddleware was recording timestamps (it was not, it was only recording the number 1 🤦)
=> feat: add ExponentialBackoffRetryStrategy and fix test middleware timestamp bug

.github/workflows/build.yaml, src/Momento.Sdk/Internal/AuthGrpcManager.cs, src/Momento.Sdk/Internal/GrpcManager.cs, src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Internal/TopicGrpcManager.cs, src/Momento.Sdk/Internal/TopicInterfaceExtensions/TopicConfigWithHeaders.cs, src/Momento.Sdk/Internal/TopicInterfaceExtensions/TopicSubscriptionConnectionStateCallbacks.cs, tests/Integration/Momento.Sdk.Tests/Retry/TopicClientRetryTest.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/MomentoLocalTestTopicConfiguration.cs, tests/Integration/Momento.Sdk.Tests/Retry/utils/RetryTestUtils.cs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1189
`MomentoLocalTopicConfiguration` is a test-specific wrapper around `ITopicConfiguration`. It uses new interfaces defined in the new `Internal/TopicInterfaceExtensions` folder to be able to add momento-local headers and subscription connection state callbacks. It's used by the new topic retry tests defined in `TopicClientRetryTest.cs`.
This way, we can add/revise topics retry tests against momento-local without making any public-facing changes.
Other edits in this PR:
- Updated docker command in CI workflow file to be able to run the test admin client used by the topic retry tests.
- Carried over the `Tuple<string, string>` to `KeyValuePair<string, string>` change Michael had recommended on a previous PR.
Assuming this …
=> chore: add topic retry tests against momento-local using internal topics config wrapper
