Momento/Incubating/README.md, Momento/Incubating/Responses/CacheDictionaryGetAllResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetResponse.cs, Momento/Incubating/Responses/CacheDictionarySetResponse.cs, Momento/Incubating/Responses/CacheDictionaryValue.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Incubating/SimpleCacheClientIncubating.cs, Momento/ScsDataClient.cs
Addresses #55.
Initial dictionary stubs for `DictionarySet`, `DictionaryGet`, and `DictionaryGetAll`. To address with customer and refine per feedback.
=> feat: Add dictionary stubs

Momento/ControlGrpcManager.cs, Momento/DataGrpcManager.cs, Momento/Exceptions/AuthenticationException.cs, Momento/Exceptions/CacheExceptionMapper.cs, Momento/HeaderInterceptor.cs, Momento/JwtUtils.cs
Format the code using the dotnet code formatter.
=> chore: Run dotnet format

IncubatingIntegrationTest/DictionaryTest.cs, Momento/ISimpleCacheClient.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/Responses/CacheDictionaryFetchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetBatchResponse.cs, Momento/Incubating/Responses/CacheDictionarySetBatchResponse.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Internal/ScsDataClient.cs, Momento/Responses/CacheGetBatchResponse.cs, Momento/Responses/CacheSetBatchResponse.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
This commit applies the "Batch" and "Fetch" terminology as outlined in the name proposal document.
=> feat: update names to be in line with name proposal

IncubatingIntegrationTest/DictionaryTest.cs, IncubatingIntegrationTest/SetTest.cs, IncubatingIntegrationTest/TestBase.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/Responses/CacheDictionaryFetchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetResponse.cs, Momento/Incubating/Responses/CacheSetAddBatchResponse.cs, Momento/Incubating/Responses/CacheSetAddResponse.cs, Momento/Incubating/Responses/CacheSetDeleteResponse.cs, Momento/Incubating/Responses/CacheSetFetchResponse.cs, Momento/Incubating/SimpleCacheClient.cs, Momento/Internal/Utils.cs, Momento/MomentoSdk.csproj, Momento/Responses/CacheGetBatchResponse.cs, Momento/Responses/CacheGetResponse.cs, Momento/SimpleCacheClient.cs, MomentoIntegrationTest/SimpleCacheControlTest.cs, MomentoIntegrationTest/SimpleCacheDataTest.cs
Closes #90 
Implement the set data structure, including: `SetAddAsync`, `SetFetchAsync`, and `SetDeleteAsync`.
=> feat: implement set data structure

IncubatingIntegrationTest/DictionaryTest.cs, IncubatingIntegrationTest/SetTest.cs, Momento/Incubating/Internal/ScsDataClient.cs, Momento/Incubating/Responses/CacheDictionaryFetchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetBatchResponse.cs, Momento/Incubating/Responses/CacheDictionaryGetResponse.cs, Momento/Internal/Utils.cs, Momento/MomentoSdk.csproj
Update to latest protos. This includes changes to the `Dictionary` responses and requests to cut over to the new names and the `Found`/`Missing` pattern.
=> fix: update to latest protos

.github/workflows/cd.yaml, .github/workflows/ci.yaml, Momento/MomentoSdk.csproj
Add extended metadata for display on the public NuGet package repository.
=> chore: add metadata and fix CI/CD for NuGet

IncubatingIntegrationTest/IncubatingIntegrationTest.csproj, Momento/MomentoSdk.csproj, MomentoIntegrationTest/MomentoIntegrationTest.csproj, MomentoTest/MomentoTest.csproj
Bumps protos and removes unnecessary elements from csproj fles.
Progress towards [#105](https://github.com/momentohq/dev-eco-issue-tracker/issues/105)
=> chore: remove build cruft

src/Momento.Sdk/Incubating/Internal/ScsDataClient.cs, src/Momento.Sdk/Incubating/Responses/CacheListRemoveAllResponse.cs, src/Momento.Sdk/Incubating/SimpleCacheClient.cs, src/Momento.Sdk/Internal/Utils.cs, tests/Integration/Momento.Sdk.Incubating.Tests/ListTest.cs
Implements `ListRemoveAll` in the SDK. This removes all elements from a list equal to a particular value.
Closes #131
=> feat: list remove all

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Configurations.cs, src/Momento.Sdk/Config/IConfiguration.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Transport/IGrpcConfiguration.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/Utils.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheDataTest.cs, tests/Unit/Momento.Sdk.Tests/ConfigTest.cs, tests/Unit/Momento.Sdk.Tests/MomentoSignerTest.cs
Moves data client gRPC deadline to gRPC configuration.
Work towards #78
=> chore: move data client deadline to grpc configuration

examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs
=> chore: update SDK version to the latest

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs
This PR changes the control plane operations to be async instead of blocking.
Closes #197
=> feat: async control commands

README.template.md
Just a first stab at including some text that gives some treatment
to our error handling and tuning considerations.  This will
surely evolve over time.
=> chore: update README to include info about error handling and tuning

examples/MomentoLoadGen/Program.cs, src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Transport/ITransportStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs
This gets rid of some straggling try/catch blocks in the loadgen and ensures that it will count throttles and other response types properly.
=> chore: update load gen to use new error handling

src/Momento.Sdk/Auth/EnvMomentoTokenProvider.cs, src/Momento.Sdk/Responses/CreateCacheResponse.cs
Just a couple tiny corrections to the docs.
=> fix: correct documentation errors

examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs, examples/MomentoFSharpApplication/MomentoFSharpApplication.fsproj, examples/MomentoFSharpApplication/Program.fs, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoLoadGen/Program.cs, examples/MomentoUsage/MomentoUsage.csproj, examples/MomentoUsage/Program.cs
Includes minor changes to pre-built config instantiation / logging
configs.
=> chore: update examples to release 0.36.0

examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs, examples/MomentoFSharpApplication/MomentoFSharpApplication.fsproj, examples/MomentoFSharpApplication/Program.fs, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoLoadGen/Program.cs, examples/MomentoUsage/MomentoUsage.csproj, examples/MomentoUsage/Program.cs
This updates the examples to SDK release version 0.37.0.
=> chore: update examples to release 0.37.0

README.ja.md, README.template.md, docs/advanced-config.ja.md
=> chore: add Japanese README and advanced config doc

src/Momento.Sdk/Momento.Sdk.csproj
Updates SDK with latest client protos
=> chore: pull latest client protos

src/Momento.Sdk/ISimpleCacheClient.cs, src/Momento.Sdk/Internal/ControlGrpcManager.cs, src/Momento.Sdk/Internal/ScsControlClient.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/FlushCacheResponse.cs, src/Momento.Sdk/SimpleCacheClient.cs, tests/Integration/Momento.Sdk.Tests/SimpleCacheControlTest.cs
The implementation for exposing the ability to clear the contents of a given cache. All the data set prior to the execution of this API will be deleted.
=> feat: Add ability to flush a given cache

examples/MomentoLoadGen/Program.cs
This is my first time doing dotnet; be savage.
Closes #229
=> feat: update load-gen example

examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoUsage/MomentoUsage.csproj
We have a few customers that need to use the eager connection
configuration to deal with cold start issues.  This commit adds
an example of how to use this configuration.
=> chore: update examples to 1.4.0, add example for eager connection config

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/IConfiguration.cs, tests/Integration/Momento.Sdk.Tests/Fixtures.cs
Remove WithLoggerFactory to prevent different components from being configured with different logger factories.
=> chore: remove WithLoggerFactory

src/Momento.Sdk/Config/Configuration.cs, src/Momento.Sdk/Config/Retry/FixedCountRetryStrategy.cs, src/Momento.Sdk/Config/Transport/StaticTransportStrategy.cs, src/Momento.Sdk/Momento.Sdk.csproj, src/Momento.Sdk/Responses/CacheDictionaryFetchResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryGetFieldsResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryIncrementResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryRemoveFieldResponse.cs, src/Momento.Sdk/Responses/CacheDictionaryRemoveFieldsResponse.cs, src/Momento.Sdk/Responses/CacheDictionarySetFieldResponse.cs, src/Momento.Sdk/Responses/CacheDictionarySetFieldsResponse.cs, src/Momento.Sdk/Responses/CacheGetResponse.cs, src/Momento.Sdk/Responses/CacheListConcatenateBackResponse.cs, src/Momento.Sdk/Responses/CacheListConcatenateFrontResponse.cs, src/Momento.Sdk/Responses/CacheListFetchResponse.cs, src/Momento.Sdk/Responses/CacheListLengthResponse.cs, src/Momento.Sdk/Responses/CacheListPopBackResponse.cs, src/Momento.Sdk/Responses/CacheListPopFrontResponse.cs, src/Momento.Sdk/Responses/CacheListPushBackResponse.cs, src/Momento.Sdk/Responses/CacheListPushFrontResponse.cs, src/Momento.Sdk/Responses/CacheListRemoveValueResponse.cs, src/Momento.Sdk/Responses/CacheSetAddElementResponse.cs, src/Momento.Sdk/Responses/CacheSetAddElementsResponse.cs, src/Momento.Sdk/Responses/CacheSetFetchResponse.cs, src/Momento.Sdk/Responses/CacheSetRemoveElementResponse.cs, src/Momento.Sdk/Responses/CacheSetRemoveElementsResponse.cs, src/Momento.Sdk/Responses/CacheSetResponse.cs, src/Momento.Sdk/docs.xml
Document set, dictionary, and list responses. Enables compiler warning for undocumented publicly visible things; zero warnings after this PR.
Closes #370
=> docs: document dictionary responses

examples/DictionaryExample/DictionaryExample.csproj, examples/DictionaryExample/Program.cs, examples/DictionaryExample/README.md, examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs, examples/MomentoExamples.sln, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoUsage/MomentoUsage.csproj
This is now based on the released 1.6.0 and is ready for review.
=> chore: bring over Dictionary example from incubating

src/Momento.Sdk/Internal/Utils.cs, tests/Integration/Momento.Sdk.Tests/CacheControlTest.cs, tests/Integration/Momento.Sdk.Tests/DictionaryTest.cs, tests/Integration/Momento.Sdk.Tests/Usings.cs, tests/Integration/Momento.Sdk.Tests/Utils.cs
=> fix: a few places where we were still using raw UUIDs for test cache names

examples/DictionaryExample/DictionaryExample.csproj, examples/DictionaryExample/Program.cs, examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoApplication/Program.cs, examples/MomentoExamples.sln, examples/MomentoFSharpApplication/MomentoFSharpApplication.fsproj, examples/MomentoFSharpApplication/Program.fs, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoLoadGen/Program.cs, examples/MomentoUsage/MomentoUsage.csproj, examples/MomentoUsage/Program.cs
For early review.  Need to get rid of the csproj changes once we have a release that contains the new name.
=> chore: update examples to use CacheClient instead of SimpleCacheClient

.github/workflows/build.yaml, CONTRIBUTING.md, Makefile, examples/DocExampleApis/DocExampleApis.csproj, examples/DocExampleApis/Program.cs, examples/DocExampleFiles/DocExampleFiles.csproj, examples/DocExampleFiles/Program.cs, examples/DocExampleFiles/README.md, examples/MomentoExamples.sln
Adds example API snippet code for the v2 README.
=> chore: add example api snippets

src/Momento.Sdk/Responses/CacheListFetchResponse.cs, tests/Integration/Momento.Sdk.Tests/ListTest.cs
Remove list length from listFetch api
- integ tests
=> feat: remove list length from listFetch api

src/Momento.Sdk/CacheClient.cs, src/Momento.Sdk/ICacheClient.cs, src/Momento.Sdk/Internal/DataGrpcManager.cs, src/Momento.Sdk/Internal/ScsDataClient.cs, src/Momento.Sdk/Responses/CacheDictionaryLengthResponse.cs, src/Momento.Sdk/Responses/CacheSetLengthResponse.cs, tests/Integration/Momento.Sdk.Tests/SetTest.cs
- Add SetLength API 
- Add corresponding integ tests
- Run integ tests
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/366
=> feat: Add SetLength API

tests/Integration/Momento.Sdk.Tests/AuthClientCacheTest.cs
This commit adds an assortment of tests against `DisposableTokenScope` objects that are composed of multiple permissions to supplement the existing tests which rely on predefined single-permission `DisposableTokenScopes` objects. Similar tests covering topics are being handled in a separate PR that adds token scoping by topic name prefix.
=> chore: adding tests for composed disposable token scopes

examples/MomentoLoadGen/Program.cs
For For https://github.com/momentohq/dev-eco-issue-tracker/issues/431
=> chore: update loadgen to be more specific for numberOfConcurrentRequests caveat

src/Momento.Sdk/Config/Middleware/ExperimentalMetricsLoggingMiddleware.cs
Follow up to https://github.com/momentohq/client-sdk-javascript/pull/998
=> chore: wrap experimental metrics json in momento object

src/Momento.Sdk/Internal/VectorIndexControlClient.cs, src/Momento.Sdk/Responses/Vector/IndexInfo.cs, tests/Integration/Momento.Sdk.Tests/Utils.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexControlTest.cs, tests/Integration/Momento.Sdk.Tests/VectorIndexDataTest.cs
Add MVI list indexes detail to IndexInfo object and update integration tests.
=> feat: add mvi list indexes detail

.github/workflows/on-push-to-release-branch.yaml
This is just a duplicate of #526 , filed against a branch in the momentohq repo so that we can let CI run.
- copy needed .dlls for unity
- set dll version
- fix which dlls to include
=> feat: update unity zip

.github/workflows/on-push-to-release-branch.yaml
Forgot to add Newtonsoft.Json.dll in the original PR https://github.com/momentohq/client-sdk-dotnet/pull/526
=> add missing Newtonsoft.Json.dll

.github/workflows/build.yaml, examples/DisposableTokens/DisposableTokens.csproj, examples/DocExampleApis/DocExampleApis.csproj, examples/MomentoApplication/MomentoApplication.csproj, examples/MomentoExamples.sln, examples/MomentoFSharpApplication/MomentoFSharpApplication.fsproj, examples/MomentoLoadGen/MomentoLoadGen.csproj, examples/MomentoUsage/MomentoUsage.csproj, examples/MomentoUsage/README.md, examples/MomentoWeb/MomentoWeb.csproj, examples/MomentoWeb/Program.cs, examples/MomentoWeb/README.md, examples/README.md, examples/TopicExample/TopicExample.csproj
Add an example that uses the .NET Web SDK. It is a copy of the basic application example.
Add a step to the github build that runs the web example to ensure we test the web SDK.
Update the examples to the latest SDK version.
Change the eager connection example to use the CreateAsync function to make it compatible with the newest versions of the SDK.
Misc fixes.
=> chore: Add a Web SDK example

src/Momento.Sdk/Internal/ScsTopicClient.cs, src/Momento.Sdk/Responses/Topic/TopicMessage.cs
Adds the sequence number to the topic message response type.
=> feat: add topic sequence number to topic message

examples/MomentoExamples.sln, examples/TopicHeartbeatExample/Program.cs, examples/TopicHeartbeatExample/TopicHeartbeatExample.csproj
Adds an example demonstrating logging a message if a heartbeat isn't
received in an interval of time.
=> chore: add example logging if heartbeat not received
